// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfV7bHwhESMe0mpLSO-_3t_HBWf7dw4g',
    appId: '1:596278734058:android:af9115646d8eb2ebcc7b93',
    messagingSenderId: '596278734058',
    projectId: 'kkm-beacon',
    databaseURL:
        'https://kkm-beacon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kkm-beacon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCfKeZt1YO3nvyYtoOogem3p-MLuJLyTQ',
    appId: '1:596278734058:ios:0f09eb8b6727c140cc7b93',
    messagingSenderId: '596278734058',
    projectId: 'kkm-beacon',
    databaseURL:
        'https://kkm-beacon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kkm-beacon.appspot.com',
    androidClientId:
        '596278734058-q9j82fk3kf8e8jonp5avfef43h97mjo7.apps.googleusercontent.com',
    iosClientId:
        '596278734058-ff9k5h4v9bdtq522bfg4frse04u5s29v.apps.googleusercontent.com',
    iosBundleId: 'com.digisailor.safecampus',
  );
}
